runtime: nodejs20
service: frontend-service
instance_class: F1

handlers:
  - url: /(.*)
    static_files: build/index.html
    upload: build/index.html

  - url: /(.*)
    static_dir: build

default_expiration: '1h'
