steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend-service', '.']
    dir: 'backend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend-service']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'backend-service',
      '--image', 'gcr.io/$PROJECT_ID/backend-service',
      '--timeout', '1000s',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars',
      'JWT_SECRET=rahasia_super_aman,JWT_EXPIRES_IN=1d,DB_HOST=34.121.20.199,DB_USER=root,DB_PASSWORD=123220024,DB_NAME=notes'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
